### ISSUE TITLE
Make install of Guix with mobile broadband connection

### ISSUE THREAD

**Issue by MorphicResonance** [Dunkmania101/custom-guix-installer#1]
It seems like not possible to make install of Guix without internet connection and if you are with 3g modem and mobile broadband connection it is not possible at all. How about including packages/drivers to make mobile network connections before the final installation phase?

It is good to have an iso which is focused on creating internet connection first because without it you can't install Giux. There is no live version where as in some other distros like debian based bunsenlabs, arch linux based, void linux based agarimos where you can boot live usb and make connection first then continue with installation process. For supporting mobile broadband connection iso should include such packages as `usb-modeswitch` ,`NetworkManager`, `mobile-broadband-provider-info`.

**Comment by Dunkmania101** [comment]
I added the packages you listed, please let me know if I missed anything else. Thanks for letting me know!

**Comment by MorphicResonance** [comment]
Need yet another package to make it work :`ModemManager` . Please add this package too.

**Comment by Dunkmania101** [comment]
Done!

**Comment by MorphicResonance** [comment]
See that github action failed for this installer. You need rerun it.

**Comment by Dunkmania101** [comment]
It's been failing for a while now, I think it has something to do with polkit. I'm trying to figure it out.

**Comment by Dunkmania101** [comment]
I don't think it's something I did because the SystemCrafters repo has the same problem.

**Comment by Dunkmania101** [comment]
Well, aparently it works again now, so that's good!
